### ISSUE TITLE
Explain S1_LANDSCAPE_DOMAIN when it include a cf instance "-001"

### ISSUE THREAD

**Issue by susanxyh** [SAP-docs/btp-connectivity#11]
### Issue description

In the document, it shows S1_LANDSCAPE_DOMAIN comes from API endpoint. So S1_LANDSCAPE_DOMAIN might include a cf instance # "-001" and this sometimes needs to be included and sometimes omitted (SAML Metadata link). 
When I go to "https://<subdomain>.authentication.us10-001.hana.ondenmand.com/saml/metadata", there is a error message: **404 Not Found**: Requested route ('<subdomain>.authentication.us10-001.hana.ondemand.com') does not exist. 
But when I change the URL to "https://<subdomain>.authentication.us10.hana.ondenmand.com/saml/metadata", I can download metadata successfully. 
**Please improve the explanation for this part.**

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

User Propagation between Cloud Foundry Applications

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/user-propagation-between-cloud-foundry-applications?version=Cloud

**Comment by Frank1Mueller** [comment]
Hi susanxyh,

thanks a lot for your feedback :) 

We will analyze the issue and get back to you soon.

Best regards

Frank

**Comment by Frank1Mueller** [comment]
Hi susanxyh,

thanks again for your contribution. 
We have discussed the issue and updated the documentation accordingly.

Best regards
Frank
