### ISSUE TITLE
User Propagation between Cloud Foundry Applications Issue - "Full authentication is required to access this resource"

### ISSUE THREAD

**Issue by aboccassiniavvale** [SAP-docs/btp-connectivity#12]
### Issue description

Hi, I was following this guide but when I try to consume the destination I get the following error "Full authentication is required to access this resource".
I have followed all the steps indicated but unfortunately the error remains.

I was wondering if this guide can still be considered valid based on the message I see when I try to create a "New Trust Configuration": "Consider using the Establish Trust button instead of using SAML. SAML is deprecated for user-interactive authentication in customer-owned accounts starting December 31, 2024. The Establish Trust button creates a trust configuration with OpenID Connect. For more information about the deprecation, including exceptions, see the release note."

Thanks,
Alessandro

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

User Propagation between Cloud Foundry Applications

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/user-propagation-between-cloud-foundry-applications

**Comment by Frank1Mueller** [comment]
Hi Alessandro,

thanks a lot for your feedback :)

We'll analyze the issue and get back to you soon.

Best regards

Frank

**Comment by Frank1Mueller** [comment]
Hi again,

we have now had a closer look at your issue.

In fact, the scenario you refer to is not affected by the deprecation announcement. There are some exceptions listed in the corresponding release note. The relevant exception is:

_The deprecation doesn't apply to the following cases:

- Principal propagation using the SAML Bearer flow. An example for this is an SAML trust configuration to accept API calls on behalf of users from another subaccount using a destination._

Best regards
Frank
