### ISSUE TITLE
Reused Screenshots can cause confusion

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-connectivity#14]
### Issue description

The screenshots after _Choose Generate a certificate signing request for option 2_ and _Choose Create and import a self-signed certificate if you want to use option_ show the System Certificate, not the CA Certificate.

This can lead to confusion.

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Configure a CA Certificate

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/configure-ca-certificate-for-principal-propagation

**Comment by Frank1Mueller** [comment]
Dear Sebastian,

thanks a lot for your feedback.

We'll analyze the issue and get back to you soon.

Best regards

Frank

**Comment by Frank1Mueller** [comment]
Hi Sebastian,

we have now analyzed your issue.

We'll update the documentation accordingly.

Thanks a lot for you valuable contribution.

Best regards

Frank
