### ISSUE TITLE
Log file ljs_trace.log does no longer exist but is still mentioned in the documentation

### ISSUE THREAD

**Issue by mbeykirch** [SAP-docs/btp-connectivity#5]
### Issue description

It seems that the former log file ljs_trace.log has been renamed to ssc_core.trc. However, it is still mentioned in the documentation.

It would also have been nice to mention such changes in the release information - that is why release information exists.

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Troubleshooting

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/cloud-connector-troubleshooting?q=ljs_trace.log

**Comment by Frank1Mueller** [comment]
Dear Martin,

thanks a lot for pointing this out. We updated the content accordingly.

Best regards
Frank

**Comment by mbeykirch** [comment]
1456923
