### ISSUE TITLE
This page is refreshing automatically every few seconds

### ISSUE THREAD

**Issue by aourzy** [SAP-docs/btp-connectivity#7]
This page is refreshing automatically every few seconds.

https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/configure-solution-management-integration

**Comment by Frank1Mueller** [comment]
Dear aourzy,

unfortunately, we could not reproduce the issue.

It might have been a temporary problem on Help Portal.

Other causes might be issues with your browser or device. In this case, please contact your administrator.


Best regards
Frank
